server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/avaliakids-auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
