server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Authorization
        - id: question-service
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path=/question-service/**
          filters:
            - StripPrefix=1
        - id: quiz-service
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/quiz-service/**
          filters:
            - StripPrefix=1
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
