server:
  port: 8082

spring:
  application:
    name: QUESTION-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/avaliakids-questions

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
